config/routes.rb
TimeSlips::Application.routes.draw do  
  resources :sheets do
    get :parse
    get :output
  end

  resources :lines

  resources :changes
  
  resources :clients
  
  root :to => "sheets#index"
end

app/models/change.rb
class Change < ActiveRecord::Base
  attr_protected :id
end

app/controllers/changes_controller.rb
class ChangesController < ApplicationController
  def index
    @changes = Change.all.sort_by{ |c| c.name.downcase }
  end

  def show
    @change = Change.find(params[:id])   
  end

  def new
    @change = Change.new
  end

  def edit
    @change = Change.find(params[:id])
  end

  def create
    @change = Change.new(params[:change])

    if @change.save
      redirect_to( changes_path, :notice => "Change created successfully.")
    else
      flash[:error] = "Error creating Change"
      render :new
    end
  end

  def update
    @change = Change.find(params[:id])

    if @change.update_attributes(params[:change])
      redirect_to( changes_path, :notice => "Change updated.")
    else
      flash[:error] = "Error updating Change"
      render :edit
    end
  end

  def destroy
    @change= Change.find(params[:id])
    @change.destroy
    flash[:notice] = "Change deleted."
    redirect_to(changes_path)
  end
end

app/helpers/changes_helper.rb
module ChangesHelper
end

app/views/changes/edit.html.haml
-title("Edit Change")

=simple_form_for @change do |f|
  =f.input :abbrev, :label => "Word to be replaced"
  =f.input :name, :label => "Replacement"
  =f.submit "Save"

app/views/changes/index.html.haml
-title("All Changes")

=link_to "New Change", new_change_path

%table{:style => 'width:500px'}
  %tr
    %td.t
      %h5 Name
    %td.t
      %h5 Destroy

  -@changes.each do |c|
    %tr
      %td.t= link_to "#{c.abbrev} -> #{c.name}", edit_change_path(c)
      %td.t= link_to "Destroy", change_path(c), :confirm => 'Are you sure?', :method => :delete

app/views/changes/new.html.haml
-title("Create New Change")

=simple_form_for @change do |f|
  =f.input :abbrev, :label => "Word to be replaced"
  =f.input :name, :label => "Replacement"
  =f.submit "Save"