config/routes.rb
TimeSlips::Application.routes.draw do  
  resources :sheets do
    get :parse
    get :output
  end

  resources :lines

  resources :changes
  
  resources :clients
  
  root :to => "sheets#index"
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :lines
  
  attr_protected :id
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all.sort_by{ |c| c.name.downcase }
  end

  def show
    @client = Client.find(params[:id])   
  end

  def new
    @client = Client.new
  end

  def edit
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new(params[:client])

    if @client.save
      redirect_to( clients_path, :notice => "Client created successfully.")
    else
      flash[:error] = "Error creating Client"
      render :new
    end
  end

  def update
    @client = Client.find(params[:id])

    if @client.update_attributes(params[:client])
      redirect_to( clients_path, :notice => "Client updated.")
    else
      flash[:error] = "Error updating Client"
      render :edit
    end
  end

  def destroy
    @client= Client.find(params[:id])
    @client.destroy
    flash[:notice] = "Client deleted."
    redirect_to(clients_path)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.haml
-title("Edit Client")

=simple_form_for @client do |f|
  =f.input :abbrev, :label => "Abbreviation to be replaced"
  =f.input :name, :label => "Replacement"
  =f.submit "Save"

app/views/clients/index.html.haml
-title("All Clients")

=link_to "New Client", new_client_path

%table{:style => 'width:500px'}
  %tr
    %td.t
      %h5 Name
    %td.t
      %h5 Destroy

  -@clients.each do |c|
    %tr
      %td.t= link_to "#{c.abbrev} -> #{c.name}", edit_client_path(c)
      %td.t= link_to "Destroy", client_path(c), :confirm => 'Are you sure?', :method => :delete

app/views/clients/new.html.haml
-title("Create New Client")

=simple_form_for @client do |f|
  =f.input :abbrev, :label => "Abbreviation to be replaced"
  =f.input :name, :label => "Replacement"
  =f.submit "Save"